//
//  DeveloperPreview.swift
//  Airbnb Clone
//
//  Created by mohamed ahmed on 11/05/2025.
//

import Foundation
class DeveloperPreview {
    static let shard = DeveloperPreview()

    var listings: [Listing] = [

        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "Mohamed Aboelsaud",
            ownerImageUrl: "IMG_1",
            numberOfBedrooms: 4,
            numberOfBathrooms: 3,
            numberOfQuests: 4,
            numberOfBeds: 4,
            pricePerNight: 299,
            imageURLs: ["i1","i2","i3","i4","i5"],
            latitude: 25.78504,
            longitude: -80.19361,
            address: "124 main street",
            city: "Mo",
            state: "Cairo",
            title: "Cairo Villa",
            rating: 4.86,
            features: [.selftCheckin,.superHost],
            amenities: [.wifi,.alarmSystem,.balcony,.laundry,.tv],
            type: .villa
        ),
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "John smith",
            ownerImageUrl: "IMG_2",
            numberOfBedrooms: 5,
            numberOfBathrooms: 2,
            numberOfQuests: 3,
            numberOfBeds: 4,
            pricePerNight: 159,
            imageURLs: ["i12","i13","i8","i9","i6"],
            latitude: 25.77504,
            longitude: -80.13361,
            address: "114 main street",
            city: "Miami",
            state: "Florida",
            title: "Miami Beach House",
            rating: 4.86,
            features: [.selftCheckin,.superHost],
            amenities: [.wifi,.alarmSystem,.balcony,.laundry,.tv],
            type: .house
        ),
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "Gianna",
            ownerImageUrl: "IMG_2",
            numberOfBedrooms: 2,
            numberOfBathrooms: 1,
            numberOfQuests: 2,
            numberOfBeds: 4,
            pricePerNight: 289,
            imageURLs: ["i4","i3","i5","i13","i6"],
            latitude: 25.74504,
            longitude: -80.12361,
            address: "103 main street",
            city: "Los Ang",
            state: "USA",
            title: "Beach House",
            rating: 4.6,
            features: [.selftCheckin,.superHost],
            amenities: [.wifi,.alarmSystem,.balcony,.laundry,.tv],
            type: .house
        ),
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "Zaid",
            ownerImageUrl: "IMG_2",
            numberOfBedrooms: 5,
            numberOfBathrooms: 2,
            numberOfQuests: 3,
            numberOfBeds: 4,
            pricePerNight: 159,
            imageURLs: ["i12","i13","i8","i9","i6"],
            latitude: 25.77504,
            longitude: -70.13361,
            address: "124 main street",
            city: "Lake Arrowhead",
            state: "California",
            title: "Miami Beach House",
            rating: 4.2,
            features: [.selftCheckin,.superHost],
            amenities: [.wifi,.alarmSystem,.balcony,.laundry,.tv],
            type: .house
        ),
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "John smith",
            ownerImageUrl: "IMG_2",
            numberOfBedrooms: 5,
            numberOfBathrooms: 2,
            numberOfQuests: 3,
            numberOfBeds: 4,
            pricePerNight: 159,
            imageURLs: ["i14","i5","i11","i5","i4"],
            latitude: 25.77504,
            longitude: -80.13361,
            address: "114 main street",
            city: "Miami",
            state: "Florida",
            title: "Miami Beach House",
            rating: 4.86,
            features: [.selftCheckin,.superHost],
            amenities: [.wifi,.alarmSystem,.balcony,.laundry,.tv],
            type: .house
        ),
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "John smith",
            ownerImageUrl: "IMG_2",
            numberOfBedrooms: 5,
            numberOfBathrooms: 2,
            numberOfQuests: 3,
            numberOfBeds: 4,
            pricePerNight: 159,
            imageURLs: ["i14","i11","i6","i9","i6"],
            latitude: 25.77504,
            longitude: -80.13361,
            address: "114 main street",
            city: "Miami",
            state: "Florida",
            title: "Miami Beach House",
            rating: 4.86,
            features: [.selftCheckin,.superHost],
            amenities: [.wifi,.alarmSystem,.balcony,.laundry,.tv],
            type: .house
        ),
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "John smith",
            ownerImageUrl: "IMG_2",
            numberOfBedrooms: 5,
            numberOfBathrooms: 2,
            numberOfQuests: 3,
            numberOfBeds: 4,
            pricePerNight: 159,
            imageURLs: ["i5","i6","i8","i7"],
            latitude: 25.77504,
            longitude: -80.13361,
            address: "114 main street",
            city: "Miami",
            state: "Florida",
            title: "Miami Beach House",
            rating: 4.86,
            features: [.selftCheckin,.superHost],
            amenities: [.wifi,.alarmSystem,.balcony,.laundry,.tv],
            type: .house
        ),
    ]

}
